---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: db01
  domain: gist.gs
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-582b7331
  image_type: c1.medium
  image_id: ami-b6089bdf
  security_groups:
  - GIST_production_default
  - GIST_production_db01
  - GIST_production_db
  - GIST_production_postgresql
  - GIST_production_postgresql_master
  - GIST_production_collectd
  - GIST_production_monit
  external_host: ec2-50-16-151-44.compute-1.amazonaws.com
  external_ip: 50.16.151.44
  internal_host: ip-10-245-102-208.ec2.internal
  internal_ip: 10.245.102.208
  zone: us-east-1c
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: web01
  domain: gist.gs
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-5c7a1832
  image_type: c1.medium
  image_id: ami-b6089bdf
  security_groups:
  - GIST_production_default
  - GIST_production_web
  - GIST_production_web01
  - GIST_production_haproxy
  - GIST_production_collectd
  - GIST_production_monit
  external_host: ec2-23-22-103-137.compute-1.amazonaws.com
  external_ip: 23.22.103.137
  internal_host: ip-10-38-191-182.ec2.internal
  internal_ip: 10.38.191.182
  zone: us-east-1c
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app01
  domain: gist.gs
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-3c2b7355
  image_type: c1.medium
  image_id: ami-b6089bdf
  security_groups:
  - GIST_production_default
  - GIST_production_app01
  - GIST_production_app
  - GIST_production_passenger
  - GIST_production_apache
  - GIST_production_collectd
  - GIST_production_monit
  external_host: ec2-107-20-62-99.compute-1.amazonaws.com
  external_ip: 107.20.62.99
  internal_host: ip-10-194-58-168.ec2.internal
  internal_ip: 10.194.58.168
  zone: us-east-1c
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
