---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: db01
  domain: gist.gs
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-2a861e44
  image_type: t1.micro
  image_id: ami-a29943cb
  security_groups:
  - GIST_production_default
  - GIST_production_db01
  - GIST_production_db
  - GIST_production_postgresql
  - GIST_production_postgresql_master
  - GIST_production_collectd
  - GIST_production_monit
  external_host: ec2-184-73-79-206.compute-1.amazonaws.com
  external_ip: 184.73.79.206
  internal_host: domU-12-31-39-12-F8-FF.compute-1.internal
  internal_ip: 10.200.251.13
  zone: us-east-1b
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: web01
  domain: gist.gs
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-6e2c2a0d
  image_type: t1.micro
  image_id: ami-a29943cb
  security_groups:
  - GIST_production_default
  - GIST_production_web
  - GIST_production_web01
  - GIST_production_haproxy
  - GIST_production_collectd
  - GIST_production_monit
  external_host: ec2-23-20-224-178.compute-1.amazonaws.com
  external_ip: 23.20.224.178
  internal_host: domU-12-31-39-02-75-57.compute-1.internal
  internal_ip: 10.248.122.165
  zone: us-east-1b
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app01
  domain: gist.gs
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-c6861ea8
  image_type: t1.micro
  image_id: ami-a29943cb
  security_groups:
  - GIST_production_default
  - GIST_production_app01
  - GIST_production_app
  - GIST_production_passenger
  - GIST_production_apache
  - GIST_production_collectd
  - GIST_production_monit
  external_host: ec2-107-22-89-32.compute-1.amazonaws.com
  external_ip: 107.22.89.32
  internal_host: domU-12-31-39-02-E5-59.compute-1.internal
  internal_ip: 10.248.234.167
  zone: us-east-1b
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
